config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "users/profile/edit/", to: "users/profiles#edit"
  get "users/profile/show/", to: "users/profiles#show"
  get "/users/:id", to: "users/accounts#show"
  patch "users/:id", to: "users/profiles#update"
  root to: "home#index"
  resources :users
  resources :rooms
  post "/rooms/:id", to: "reservations#create", as: "room_reservation"
  resources :homes
  resources :reservations

  resources :rooms do
    resources :reservations, only: [:create]
  end

  get "room/search", to: "rooms#search"

  resources :users do
    collection do
      get "search"
    end
  end

  # GET /rooms/in_area/:area
  get "/rooms/in_area/:area", to: "rooms#in_area"
  # GET /rooms/search/:query
  get "/rooms/search/:query", to: "rooms#search"

  get "room/result", to: "rooms#result", as: "room_result"

  get "reservation/confirm", to: "reservations#confirm"
  post "reservation/confirm", to: "reservations#confirm"
  get "rooms/:id/reservations", to: "rooms#show"
end

app/models/room.rb
class Room < ApplicationRecord
  validates :roomname, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user, optional: true
  has_one :reservation
  has_many :reservations
  has_many :reservations, dependent: :destroy

  mount_uploader :room_image, RoomImageUploader

  # scopeで検索条件を設定する
  scope :in_area, ->(area) { where("address LIKE ?", "%#{area}%") }
  scope :search, ->(query) { where("roomname LIKE :query OR description LIKE :query", query: "%#{query}%") }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
  @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new(room_id: @room.id)
  end

  def new
    @room = Room.new
    @user = current_user
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to @room, notice: '宿泊施設を登録しました'
    else
      flash[:alert] = "必須項目に入力してください"
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to @room, notice: '宿泊施設情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_url, notice: '宿泊施設を削除しました'
  end

  def in_area
    @rooms = Room.in_area(params[:area])
  end

  def search
    @rooms = Room.search(params[:query])
  end

  def result
    @rooms = Room.all
    @rooms = @rooms.in_area(params[:area]) if params[:area].present?
    @rooms = @rooms.search(params[:query]) if params[:query].present?
    @count = @rooms.count
  end

    private

  def confirm_room_params
    params.require(:room).permit(:checkin_at, :checkout_at, :person_count, :room_id, :calc_price, :room_image).merge(user_id: current_user.id)
  end

  def room_params
    params.require(:room).permit(:roomname, :description, :price, :address, :room_image, :user_id)
  end

end
      

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<% provide(:title, "Edit Room") %>
<h1>施設情報の編集</h1>

<%= form_with model: @room, url: room_path(@room), local: true do |f| %>

  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :施設画像 %>
    <%= f.file_field :room_image %>
  </div>

  <div class="form-group">
    <%= f.label :施設名 %>
    <%= f.text_field :roomname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :住所 %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :料金 %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <%= f.submit "更新", class: "btn btn-primary" %>

<% end %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h2>登録済み施設一覧</h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">画像</th>
      <th scope="col">施設名</th>
      <th scope="col">紹介文</th>
      <th scope="col">料金</th>
      <th scope="col">作成日</th>
      <th scope="col">編集</th>
      <th scope="col">削除</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <% if room.user_id == current_user.id %>
      <tr>
      <th scope="row"><%=room.room_id%></th>
      <td>
      <% if room.room_image.present? %>
        <%= image_tag room.room_image.url(:room_image), alt: "room image", width: 120, height: 60 %>
      <% else %>
        <%= image_tag "/images/default-room-image.png", alt: "Default room image", width: 120, height: 60 %>
      <% end %>
      </td>

        <td><%= link_to room.roomname, room_reservations_path(room.id) %></td>
        <td><%= room.description %></td>
        <td><p>¥<%= room.price %>~</p></td>
        <td><%= room.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '編集', edit_room_path(room) %></td>
        <td><%= link_to '削除', room_path(room), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
      <% end%>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h2>施設新規登録</h2>

<% if @room.errors.any? %>
  <div class="alert alert-danger">
    <h4>以下のエラーがあります</h4>
    <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @room, url: rooms_path, local: true do |f| %>

  <%= f.label :施設画像 %>
  <%= f.file_field :room_image %>
  
  <div class="form-group">
    <%= f.label :施設名 %>
    <%= f.text_field :roomname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :住所 %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :料金 %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <%= f.hidden_field :room_id, value: @room.id %>

  <%= f.submit "登録", class: "btn btn-primary" %>
  
<% end %>

app/views/rooms/result.html.erb
<div class="search-field">
  <%= form_tag room_result_path, method: :get do %>

    <%= label_tag :area, "エリア検索" %>
    <%= text_field_tag :area, params[:area], placeholder: "例：東京" %>
    <%= label_tag :query, "フリーワード検索" %>
    <%= text_field_tag :query, params[:query], placeholder: "例：和室" %>
    <%= submit_tag "検索" %>

  <% end %>
</div>

<div class="search-results">
  <% if @rooms.present? %>
    <h3>検索結果：<%= @count %>件</h3>
    <div class="card" style="width: 18rem;" >
      <% @rooms.each do |room| %>
        <div class="room_image">
          <% if room.room_image.present? %>
            <%= image_tag room.room_image.url(:room_image), class:"card-img-top", alt: "room image" %>
          <% else %>
            <%= image_tag "/images/default-room-image.png", class:"card-img-top", alt: "Default room image" %>
          <% end %>
        </div>
        <div class="card-body">
          <h2 class="card-title"><%= room.roomname %></h2>
          <p class="card-text"><%= room.description %></p>
          <p class="card-text"><%= room.address %></p>
          <p class="card-text">料金:¥ <%= room.price %>~</p>
          <%= link_to "詳細ページへ", room_reservations_path(room_id: room.id), class:"btn btn-primary" %>
        </div>
      <% end %>
    </div> 
  <% else %>
    <h3>検索結果：０件</h3>
    <%= link_to "戻る", :back %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h2>施設詳細</h2>

<div class="room-show">
  <div class="room-show-container">
    <div class="room-show-image">
      <% if @room.room_image.present? %>
        <%= image_tag @room.room_image.url(:room_image), alt: "room image", width: 300, height: 200  %>
      <% else %>
        <%= image_tag "/images/default-room-image.png", alt: "Default room image",width: 300, height: 200   %>
      <% end %>
    </div>
    <div class="room-show-information">
      <div>
        <h3><%= @room.roomname %></h3>
      </div>

      <div>
        <%= @room.address %>
      </div>

      <div>
        <%= @room.description %>
      </div>

      <div>
        <p>¥<%= @room.price %>~</p>
      </div>

      <div class="reservation-form">
        <%= form_with model: @reservation, method: :post, url: reservation_confirm_path do |f| %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        
          <%= f.label :checkin_at, "開始日" %>
          <%= f.date_field :checkin_at, class: "form-control mb-4", value: @reservation.checkin_at %>

          <%= f.label :checkout_at, "終了日" %>
          <%= f.date_field :checkout_at, class: "form-control mb-4", value: @reservation.checkout_at %>
          

          <%= f.label :person_count, "宿泊人数" %>
          <%= f.number_field :person_count, class: "form-control mb-4" %>
          <%= f.submit"予約する", class: "btn btn-primary form-contro" %>
          <%= link_to "戻る", :back;%>
        <% end %>     
      </div>
    </div>
  </div>
</div>