config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "users/profile/edit/", to: "users/profiles#edit"
  get "users/profile/show/", to: "users/profiles#show"
  get "/users/:id", to: "users/accounts#show"
  patch "users/:id", to: "users/profiles#update"
  root to: "home#index"
  resources :users
  resources :rooms
  post "/rooms/:id", to: "reservations#create", as: "room_reservation"
  resources :homes
  resources :reservations

  resources :rooms do
    resources :reservations, only: [:create]
  end

  get "room/search", to: "rooms#search"

  resources :users do
    collection do
      get "search"
    end
  end

  # GET /rooms/in_area/:area
  get "/rooms/in_area/:area", to: "rooms#in_area"
  # GET /rooms/search/:query
  get "/rooms/search/:query", to: "rooms#search"

  get "room/result", to: "rooms#result", as: "room_result"

  get "reservation/confirm", to: "reservations#confirm"
  post "reservation/confirm", to: "reservations#confirm"
  get "rooms/:id/reservations", to: "rooms#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoyakuSample12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
  </head>

  <body>
    <header>
      <div class="header-logo">
        <%= link_to "PoteoanShare", root_path %>
      </div>
      <div class="nav-contents">
        <% if user_signed_in? %>

          <div class="profile-image">
            <% if current_user.profile_image.present? %>
              <%= image_tag current_user.profile_image.url(:profile_image), alt: "Profile image" %>
            <% else %>
              <%= image_tag "/images/default-profile-image.png", alt: "Default profile image", width: 40, height: 40  %>
            <% end %>
          </div>
         
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"  >
              <%= current_user.username %>
            </button>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1"> 

              <li><%= link_to "アカウント編集", edit_user_registration_path, class:"dropdown-item" %></li>
              <li><%= link_to "アカウント",  "/users/:id", class:"dropdown-item" %></li>
              <li><%= link_to "プロフィール編集", users_profile_edit_path, class:"dropdown-item" %></li>
              <li><%= link_to "プロフィール", users_profile_show_path, class:"dropdown-item" %></li>
              <li><%= link_to "施設新規登録", new_room_path, class:"dropdown-item" %></li>
              <li><%= link_to "登録済み施設一覧",rooms_path, class:"dropdown-item" %></li>
              <li><%= link_to "予約済み施設一覧",reservations_path, class:"dropdown-item" %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'dropdown-item' %></li>
            </ul>
          </div>  
        <%else%>
          <%= link_to "ログイン", new_user_session_path %>
          <%= link_to "新規作成", new_user_registration_path %>
        <% end %>
      </div>

    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
</html>